server {
    listen 80;

    # Defer DNS resolution to request time — prevents startup failure on ECS
    # where 'backend' is not on the same network.
    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Used on EC2 only since on ECS the backend is on the same network and can be accessed directly via 'backend:8080'.
    location /api/ {
        set $backend http://backend:8080;
        proxy_pass         $backend;
        proxy_http_version 1.1;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }
}
